language: cpp
os:
    - linux
    - osx
env:
    - BUILD_SHARED_LIBS=ON
    - BUILD_SHARED_LIBS=OFF
sudo: false
addons:
    apt:
        sources:
            - kubuntu-backports
        packages:
            - cmake
script:
    - cmake -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} .
    - cmake --build .
